# Generated by Django 5.2.1 on 2025-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='art_works/'),
        ),
    ]
